--NO RETURN 


CREATE PROCEDURE CREATESTUDENTS 
@EVENTS VARCHAR(100)
AS
BEGIN

INSERT INTO SPORTS_DETAILS (EVENTS) VALUES(@EVENTS);

END


-----------------------------------------------------------------


--WITH RETURN
-- TO ALTER THE PROCEDURE USE KEYWORD ALTER INSTAED OF CREATE

ALTER PROCEDURE CREATESTUDENTS 
@EVENTS VARCHAR(100)
AS
BEGIN

INSERT INTO SPORTS_DETAILS (EVENTS) VALUES(@EVENTS);
SELECT * FROM SPORTS_DETAILS ;
END



EXECUTE CREATESTUDENTS 'GOOGLE';

SELECT * FROM SPORTS_DETAILS;