/*TRIGGER*/

/*1. USING FOR, for UPDATION WITH TRIGGER*/

CREATE TABLE [PERSONLOG](
LOGID INT IDENTITY(1,1) NOT NULL,
ID INT NOT NULL,
OPERATION VARCHAR(10) NOT NULL,
UPDATEDDATE DATETIME NOT NULL);


/*2*/

CREATE TRIGGER PERSONforTRIGGER
ON PERSON1
FOR
UPDATE
AS

INSERT INTO dbo.PERSONLOG(ID, OPERATION, UPDATEDDATE)
SELECT ID, 'UPDATE', GETDATE() FROM DELETED;

UPDATE PERSON1 SET NAME='RAMU' WHERE ID=2

SELECT * FROM PERSON1;




/*3*/
CREATE TRIGGER PERSONinsteadofTRIGGER
ON PERSON1
INSTEAD OF
UPDATE
AS

INSERT INTO dbo.PERSONLOG(ID, OPERATION, UPDATEDDATE)
SELECT ID, 'UPDATE', GETDATE() FROM DELETED;

UPDATE PERSON1 SET NAME='RAM' WHERE ID=3

SELECT * FROM PERSONLOG;



