/*VIEWS*/

SELECT * FROM PERSON1;
/* 1.CREATE A VIEW*/

CREATE VIEW EMPLOYEESHORT 
AS
SELECT NAME, PHONE FROM PERSON1;

/*2.EXECUTE*/
SELECT * FROM EMPLOYEESHORT;


/*3*/
CREATE VIEW EMPLOYEEDETAILS 
AS
SELECT EMP_NAME, PHONE, EMP_SALARY,EXPERIENCE FROM EMPLOYEE_DETAILS;

SELECT * FROM EMPLOYEEDETAILS;

/*4*/

CREATE VIEW EMPLOYEDETAIL
AS 
SELECT EMP_NAME, PHONE, EMP_SALARY,EXPERIENCE,PLACE, DEPT_NAME
FROM EMPLOYEE_DETAILS
CROSS JOIN DEPARTMENT
WHERE EMPLOYEE_DETAILS.DEPT_ID=DEPARTMENT.DEPT_ID

SELECT * FROM EMPLOYEDETAIL;
