CREATE DATABASE THOUGHTPRACTISE1;
USE THOUGHTPRACTISE1;


/*CREATE A TABLE*/

CREATE TABLE [EMPLOYEEE1](
[EMP_ID] [INT] IDENTITY(1,1) NOT NULL ,
[EMP_NAME][VARCHAR](20),
[PHONE][VARCHAR](30), /*use bigint*/
[EMP_DOB] [VARCHAR](20),
[EMP_DEPT][VARCHAR](20),
[EMP_SALARY][INT],
[EMP_MAILID][VARCHAR](20),
)



/*ADDING A FOREIGN KEY TO A TABLE*/
ALTER TABLE EMPLOYEE_DETAILS 
ADD CONSTRAINT FK_EMPLOYEE_DETAILS 
FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID) 
ON DELETE CASCADE
ON UPDATE CASCADE ;


/*TABLE*/
CREATE TABLE [DEPARTMENT](
[DEPT_ID] [INT]  CONSTRAINT PK_DEPAERTMENT PRIMARY KEY ,
[DEPT_NAME][VARCHAR](20),
[PLACE][VARCHAR](30), 
)


EXEC SP_RENAME 'EMPLOYEEE1', 'EMPLOYEE';/*SYNTAX TO RENAME A TABLE*/

ALTER TABLE EMPLOYEE ADD PRIMARY KEY(EMP_ID);/* Add column*/


EXEC SP_RENAME 'EMPLOYEE', 'EMPLOYEE_DETAILS'

EXEC SP_RENAME  'EMPLOYEE_DETAILS.EMP_DOB','DATE_OF_BIRTH','COLUMN'; /*rename a column*/

/*ADD A NEW RECORD */
ALTER TABLE EMPLOYEE_DETAILS ADD EMP_RECORD[VARCHAR](50); 
ALTER TABLE EMPLOYEE_DETAILS ADD EMP_NAME[VARCHAR](50);

ALTER TABLE EMPLOYEE_DETAILS ADD DEPT_ID [INT];

ALTER TABLE EMPLOYEE_DETAILS ADD AGE [INT];

/*check*/
ALTER TABLE EMPLOYEE_DETAILS 
ADD EXPERIENCE [INT] 
CONSTRAINT CHK_EXPERIENCE_CHECK 
CHECK(EXPERIENCE>0 AND EXPERIENCE<50);





/*INSERTION*/
INSERT INTO EMPLOYEE(EMP_NAME,PHONE,EMP_DOB,EMP_DEPT,EMP_SALARY,EMP_MAILID)
VALUES
('ABHI','623234234','20-01-2000','TECHNICAL','120000','ABHI@GMAIL.COM'),
('BHUVAN','909123823','2-12-2000','TRAINEE','20000','BHUVAN@GMAIL.COM'),
('KAMALESH','723234234','4-4-2004','SUPPORT','320000','DUNDUN@GMAIL.COM'),
('DOGINDER SINGH','812234234','06-7-2000','ANALYST','180000','DOGI@GMAIL.COM'),
('MOHAN','718934234','04-08-2000','TESTING','64000','MOHAN@GMAIL.COM'),
('SHREYAS','785234234','08-08-2001','IT','40000','shreyas@GMAIL.COM'),
('AVI','785234753','08-07-2001','HR','45000','avi@GMAIL.COM')




/*SELECT * FROM EMPLOYEEE1;*/
SELECT * FROM EMPLOYEE_DETAILS;
SELECT * FROM DEPARTMENT;

/*TRUNCATE TABLE EMPLOYEE;*/
/*DROP TABLE EMPLOYEE;*/

/*DELETE A PARTICULAR RECORD*/
DELETE FROM EMPLOYEE WHERE EMP_NAME = 'ABHI';



ALTER TABLE EMPLOYEE_DETAILS DROP COLUMN EMP_NAME; /* delete a column*/
 ALTER TABLE EMPLOYEE_DETAILS DROP COLUMN EMP_RECORD;



/*UPDATE THE RECORD*/
UPDATE EMPLOYEE_DETAILS 
SET EMP_SALARY = 1000000 
WHERE EMP_ID = 2;



 /*ALIAS NAME*/
SELECT EMP_ID AS ID FROM EMPLOYEE_DETAILS;
SELECT * FROM TABLE EMPLOYEE_DETAILS  AS EMPLOYEE_DETAILS 




/*1*/
SELECT EMP_NAME
FROM EMPLOYEE_DETAILS
WHERE EMP_SALARY>20000;

/*2*/
SELECT DATE_OF_BIRTH
FROM EMPLOYEE_DETAILS
WHERE EMP_NAME='AVI';

/*3*/
UPDATE EMPLOYEE_DETAILS
SET EXPERIENCE=3
WHERE EMP_ID>6;

UPDATE EMPLOYEE_DETAILS
SET EXPERIENCE=5
WHERE EMP_ID=2;


UPDATE EMPLOYEE_DETAILS
SET EXPERIENCE=10
WHERE EMP_ID=6;


UPDATE EMPLOYEE_DETAILS
SET EXPERIENCE=7
WHERE EMP_ID=3;

UPDATE EMPLOYEE_DETAILS
SET EXPERIENCE=8
WHERE EMP_ID=5;

/* DISTINCT*/
SELECT DISTINCT EMP_DEPT, EMP_SALARY FROM EMPLOYEE_DETAILS ;

/*BETWEEN*/
SELECT * FROM EMPLOYEE_DETAILS 
WHERE EMP_SALARY BETWEEN 20000 AND 50000;

/*ORDER BY*/
SELECT * FROM EMPLOYEE_DETAILS 
WHERE EMP_SALARY BETWEEN 20000 AND 50000
ORDER BY EMP_SALARY ASC;


/*GROUP BY*/
SELECT EMP_DEPT, EMP_SALARY
FROM EMPLOYEE_DETAILS 
WHERE (EMP_SALARY>45000)
GROUP BY EMP_DEPT , EMP_SALARY;


/*Alternative solution is disable all constraints, 
do the update and then enable the constraints again like this. 
Very useful when updating test data in test environments.*/

/* UPDATION OF DEPT_ID*/
exec sp_MSforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"

update EMPLOYEE_DETAILS set DEPT_ID=2 where EMP_ID=3
update EMPLOYEE_DETAILS set DEPT_ID=1 where EMP_ID=2

exec sp_MSforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all"





SELECT * FROM EMPLOYEE_DETAILS;

/*LIKE OPERATOR*/
SELECT * FROM EMPLOYEE_DETAILS WHERE PHONE LIKE  '%3';
SELECT * FROM EMPLOYEE_DETAILS WHERE PHONE LIKE  '9%';

SELECT COUNT(EMP_ID) AS COUNT FROM EMPLOYEE_DETAILS;/*COUNT*/

/*SUM*/
SELECT SUM(EMP_SALARY) 
AS TOTAL_SALARY 
FROM EMPLOYEE_DETAILS;

/*UPDATE*/
UPDATE EMPLOYEE_DETAILS
SET EMP_SALARY = (EMP_SALARY+EMP_SALARY*0.25)
 WHERE (EMP_SALARY=20000);

 /*MAX*/
 SELECT MAX(EMP_SALARY)
 AS MAX_SALARY 
FROM EMPLOYEE_DETAILS;


/*MIN*/
 SELECT MIN(EMP_SALARY)
 AS MIN_SALARY 
FROM EMPLOYEE_DETAILS;

/*AVG*/
 SELECT AVG(AGE)
 AS AVERAGE_AGE 
FROM EMPLOYEE_DETAILS;


/*all details of person who is in technical department
 and salary is greater than 20000*/

 SELECT * FROM EMPLOYEE_DETAILS 
 WHERE (EMP_SALARY>20000 AND EMP_DEPT='IT');

 /*UPPER*/
 SELECT UPPER(EMP_NAME) 
 AS  UPPER_CASE FROM EMPLOYEE_DETAILS;


 /*CONCAT*/
 SELECT CONCAT(EMP_ID,EMP_DEPT)
 AS CONCAT FROM EMPLOYEE_DETAILS;

 /*LENGTH*/
 SELECT LEN('RAHUL') AS LENGTH;

 /*REVERSE*/
 SELECT REVERSE('SHREYAS') 
 AS REVERSED ;

 /*SUBSTRING*/
SELECT SUBSTRING('SHREYAS',2,3) 
 AS SUB_NAME ;

