CREATE DATABASE THOUGHTPRACTISE;
USE THOUGHTPRACTISE;


CREATE TABLE [STUDENT](  
[STUDENT_ID][INT],
[STUDENT_NAME][VARCHAR](20),
[SPORTS][VARCHAR](10),
[BLOOD_GROUP][VARCHAR] (20),
[AGE] [INT] 
);

INSERT INTO STUDENT(STUDENT_ID,STUDENT_NAME,SPORTS,BLOOD_GROUP,AGE)
VALUES
(3,'Prajwal','Golf','O+',21),
(4,'Vaibhav','Hockey','AB+',20);





SELECT * FROM STUDENT;


SELECT * FROM SPORTS_DETAILS;
