CREATE TABLE [PERSON](
[ID] [INT] IDENTITY(1,1) NOT NULL,
[NAME][VARCHAR](20),
[PHONE][VARCHAR](30), 
[SALARY][INT],
[MAILID][VARCHAR](20),
)

/*indexing*/
CREATE INDEX idx_one
ON PERSON1 (SALARY ASC);

sp_Helpindex PERSON1;

DROP INDEX PERSON1.idx_one;




INSERT INTO PERSON(NAME,PHONE,SALARY,MAILID)
VALUES
('ABHI','623234234',120000,'ABHI@GMAIL.COM');


SELECT * FROM PERSON;
SELECT * FROM PERSON1;

EXEC SP_RENAME  'PERSON.MAILID','EMAIL','COLUMN';

EXEC SP_RENAME 'PERSON', 'PERSON1';

ALTER TABLE PERSON1 ADD AGE [INT];
ALTER TABLE PERSON1 ADD RECORD [VARCHAR] (20);

ALTER TABLE PERSON1 DROP COLUMN RECORD;
ALTER TABLE PERSON1 DROP COLUMN EMAIL;

ALTER TABLE PERSON1 ALTER COLUMN NAME[VARCHAR](90);


UPDATE PERSON1
SET SALARY = 1000000 
WHERE ID = 2;



SELECT * FROM PERSON1 WHERE ID=1;

DELETE FROM PERSON1 WHERE ID=1;

SELECT NAME AS ENAME FROM PERSON1;/*ALIAS*/

SELECT COUNT(ID) AS COUNT FROM PERSON1;/*COUNT*/

/*SUM*/
SELECT SUM(SALARY) 
AS TOTAL_SALARY 
FROM PERSON1;

/*UPDATE*/
UPDATE PERSON1
SET SALARY = (SALARY+SALARY*0.25)
 WHERE (SALARY=40000);

 UPDATE PERSON1
SET SALARY = (SALARY+SALARY/30)
 WHERE (SALARY=70000);


 /* DISTINCT*/
SELECT DISTINCT NAME
FROM PERSON1;

SELECT DISTINCT ID
FROM PERSON1;

/* DISTINCT*/
SELECT DISTINCT NAME, SALARY 
FROM PERSON1 ;

UPDATE PERSON1
SET SALARY = (SALARY+SALARY*0.25)
 WHERE (SALARY=40000);

 SELECT * FROM PERSON1 /*EQUALS*/
 WHERE ID=1;

  SELECT * FROM PERSON1 /*NOT EQUALS*/
 WHERE ID!=1;


 SELECT * FROM PERSON1 /*GREATER OR EQUALT TO*/
 WHERE ID>=3;

  SELECT * FROM PERSON1 /*LESSER OR EQUAL TO*/
 WHERE ID<=3;

 SELECT * FROM PERSON1
 WHERE ID<>5;

 /*AND*/
 SELECT * FROM PERSON1 
 WHERE ID =3 AND NAME='AVI';

 /*OR*/
 SELECT * FROM PERSON1 
 WHERE ID =5 OR NAME='AVI';

 SELECT * FROM PERSON1;
 